generator_config:
  latent_dim : 256
  out_channels: 1
  k_width: 3
  k_heigth: 3
  k_filters: 32
  scale_factor: 2


discriminator_config:
  in_channels: 1
  out_channels: 1
  k_width: 3
  k_heigth: 3
  k_filters: 32
  scale_factor: 2
  ksize_down: 2
  stride_down: 2


gan_config: 
  latent_dim: 256
  lr_g: 8e-4
  lr_d: 8e-4
  model_name: 'gansynth_test'
  num_epochs: 100
  add_loss: 0
  add_figure: 0
  save_ckpt: 0
  critic_iteration: 1
  lambda_gp: 10


dataset:
  batch_size: 6
  root_dir: "/fast-1/atiam22-23/nsynth/"
  maxi: 17.838465