generator_config:
  latent_dim : 100
  out_channels: 1
  num_filters: 64
  num_classes: 10
  kernel_size: 5

discriminator_config:
  in_channels: 1
  num_filters: 64
  num_classes: 10
  kernel_size: 5
  dropout: 0.3

gan_config: 
  latent_dim: 100
  lr_g: 1e-4
  lr_d: 1e-4
  model_name: 'test'
  num_epochs: 100
  add_loss: 31
  add_figure: 31
  save_ckpt: 31

batch_size: 32