generator_config:
  latent_dim : 256
  out_channels: 1
  k_width: 3
  k_heigth: 3
  k_filters: 32
  scale_factor: 2


discriminator_config:
  in_channels: 1
  out_channels: 1
  k_width: 3
  k_heigth: 3
  k_filters: 32
  scale_factor: 2
  ksize_down: 2
  stride_down: 2


gan_config: 
  latent_dim: 256
  lr_g: 2e-4
  lr_d: 4e-4
  model_name: 'gansynth_test_cond_5'
  num_epochs: 100
  add_loss: 200
  add_figure: 200
  save_ckpt: 200
  critic_iteration: 1
  lambda_gp: 1


dataset:
  batch_size: 6
  root_dir: "/fast-1/atiam22-23/nsynth/"
  maxi: 12.347074 # valeur par défaut pour nsynth (avec que les samples acoustiques)