generator_config:
  latent_dim : 256
  out_channels: 1
  k_width: 3
  k_heigth: 3
  k_filters: 32
  scale_factor: 2


discriminator_config:
  in_channels: 1
  out_channels: 1
  k_width: 3
  k_heigth: 3
  k_filters: 32
  scale_factor: 2
  ksize_down: 2
  stride_down: 2


gan_config: 
  latent_dim: 256
  lr_g: 2e-4
  lr_d: 4e-4
  model_name: gansynth
  num_epochs: 100
  add_loss: 400
  add_figure: 400
  save_ckpt: 400
  critic_iteration: 1
  lambda_gp: 1


dataset:
  batch_size: 6
  resample_rate: 16000
  signal_duration: 4
  root_dir: /data/drums/audio/
  maxi: 12.6411705 # default value for nsynth (with only acoustic samples) - 12.347074 | for drums : 12.6411705



# Hydra config
hydra:
  verbose: __main__
  run:
    dir: ./runs/${gan_config.model_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog